<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_Cars_iCheck-helper</name>
   <tag></tag>
   <elementGuidId>d51723ae-3a75-45e7-9fc3-0869429e07a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/form/div/div[2]/div/div[22]/div[1]/div/div[2]/ul/li[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='content']/form/div/div[2]/div/div[22]/div[1]/div/div[2]/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='content']/form/div/div[2]/div/div[22]/div[1]/div/div[2]/ul/li[3]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='content']/form/div/div[2]/div/div[22]/div/div/div[2]/ul/li[3]/label/div/ins</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//li[3]/label/div/ins</value>
   </webElementXpaths>
</WebElementEntity>
